name: PHP Test Runner

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2  
    - name: Setup PHP and Run Test
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
      run: "php test/test.php"